#!/bin/bash
usage(){
echo "usage: LSS_submit <bids_dir> <fmriprep_folder> <output_dir> <exp_start volume>"
}
bids_dir=$1
fmriprep_folder=$2
output_dir=$3
expstart_vol=$4
if [ "$#" -eq 3 ]
then
	mkdir -p $output_dir/singletrial_GLM
	subs=$(cut -f 1 $bids_dir/participants.tsv|tail -n +2)
	for sub in $subs
	do
	sub_dir="$output_dir/singletrial_GLM/$sub"
	mkdir -p $sub_dir 
	neurogliaSubmit -j LongSkinny 'matlab -nosplash -nodisplay -r "addpath(genpath('"'/project/6007967/hyang336/matlab/'"')); singless_LSS('"'$bids_dir'"','"'$fmriprep_folder'"','"'$output_dir'"','"'$sub'"','"$expstart_vol"'); exit;"' 
	sleep 3
	done
else
usage
exit 1
fi

